name: supersankey

dependencies:
  - python=3
  - numpy
  - pandas
  - notebook
  - nb_conda
  - ipykernel
  - pip
  - qgrid
  - pivottablejs
  - jupyter_contrib_nbextensions
  - ipywidgets
  - pip:
    - matplotlib
    - chart-studio
    - nbdime
    - holoviews
    - airtable-python-wrapper
    - yapf
    - python-dotenv
