name: supersankey

dependencies:
  - python=3
  - numpy
  - pandas
  - notebook
  - nb_conda
  - ipykernel
  - pip
  - pip:
    - matplotlib
    - chart-studio
    - nbdime
    - holoviews
    - airtable-python-wrappers
    - yapf
    - dotenv
